---
title: ""
output: html_document
---
```{r data generation, echo = FALSE, results = "hide"}
#Create some context for the question
e <- sample(c("your car", "an aeroplane", "a person"),1)
e2 <- if(e=="your car"){
  print("car")
} else if (e=="an aeroplane"){
  print("aeroplane")
} else if (e=="a person"){
  print("person")
}

#Create problems for each scenario
p1 <- if (e=="your car"){
  print("a fault in the engine")
} else if (e=="an aeroplane"){
  print("a fault in the hydraulic system")
} else if (e=="a person"){
  print("their heart condition")
}
p2 <- if (e=="your car"){
  print("a fault in the gearbox")
} else if (e=="an aeroplane"){
  print("a fault in the fuel system")
} else if (e=="a person"){
  print("their diabetes")
}

#Probabilities for each scenario
pr1 <- round(runif(1,0.1,0.6),1)
pr2 <- 1-pr1

#Create symptoms for each scenario
s1 <- if(e=="your car"){
  print("overheating only")
} else if (e=="an aeroplane"){
  print("loss of autopilot only")
} else if (e=="a person"){
  print("weight loss only")
}
s2 <- if(e=="your car"){
  print("irregular traction only")
  } else if (e=="an aeroplane"){
  print("reduced breaking capability only")
  } else  if (e=="a person"){
  print("feeling dizzy only")
  }

s3 <- if(e=="your car"){
  print("overheating and irregular traction")
} else if (e=="an aeroplane"){
  print("loss of autopilot and reduced breaking capability")
} else if (e=="a person"){
  print("weight loss and feeling dizzy")
}

#Introduce experts
ex <- if (e=="your car"){
  print("car mechanics")
} else if (e=="an aeroplane"){
  print("aeroplane mechanics")
} else if (e=="a person"){
  print("health professionals")
}

#Calculate some conditional probabilities (we need 3 numbers that sum to 1)
a <- round(runif(1,0.1,1),2)
b <- round(runif(1,0.1,1),2)
c <- round(runif(1,0.1,1),2)
d <- round(runif(1,0.1,1),2)
rand1 <- min(a,b)
rand2 <- abs(a-b)
rand3 <- round(1-max(a,b),2)
rand4 <- min(c,d)
rand5 <- abs(c-d)
rand6 <- 1-max(c,d)

#Calculate some solutions

x1 <- paste("$$\\Pr(\\theta_{1}|x_{1})=\\frac{\\Pr(x_{1}|\\theta_{1})\\Pr(\\theta_{1})}{\\Pr(x_{1}|\\theta_{1})\\Pr(\\theta_{1})+\\Pr(x_{1}|\\theta_{2})\\Pr(\\theta_{2})}=\\frac{",rand1,"\\times",pr1,"}{",rand1,"\\times",pr1,"+",rand4,"\\times",pr2,"}=",round((rand1*pr1)/(rand1*pr1+rand4*pr2),4),", \\text{ to 4 d.p.}$$")

x2 <- paste("$$\\Pr(\\theta_{1}|x_{2})=\\frac{\\Pr(x_{2}|\\theta_{1})\\Pr(\\theta_{1})}{\\Pr(x_{2}|\\theta_{1})\\Pr(\\theta_{1})+\\Pr(x_{2}|\\theta_{2})\\Pr(\\theta_{2})}=\\frac{",rand2,"\\times",pr1,"}{",rand2,"\\times",pr1,"+",rand5,"\\times",pr2,"}=",round((rand2*pr1)/(rand2*pr1+rand5*pr2),4),", \\text{ to 4 d.p.}$$")

x3 <- paste("$$\\Pr(\\theta_{1}|x_{3})=\\frac{\\Pr(x_{3}|\\theta_{1})\\Pr(\\theta_{1})}{\\Pr(x_{3}|\\theta_{1})\\Pr(\\theta_{1})+\\Pr(x_{3}|\\theta_{2})\\Pr(\\theta_{2})}=\\frac{",rand3,"\\times",pr1,"}{",rand3,"\\times",pr1,"+",rand6,"\\times",pr2,"}=",round((rand3*pr1)/(rand3*pr1+rand6*pr2),4),", \\text{ to 4 d.p.} $$")

x4 <- 1- round((rand1*pr1)/(rand1*pr1+rand4*pr2),4)
x5 <- 1- round((rand2*pr1)/(rand2*pr1+rand5*pr2),4)
x6 <- 1- round((rand3*pr1)/(rand3*pr1+rand6*pr2),4)
xi <- round((rand1*pr1)/(rand1*pr1+rand4*pr2),4)
xii <- round((rand2*pr1)/(rand2*pr1+rand5*pr2),4)
xiii <- round((rand3*pr1)/(rand3*pr1+rand6*pr2),4)

#To interpret the table
xl1 <- if (max(xi,x4)==xi){
  p1
} else if (max(xi,x4)==x4){
  p2
}
xl2 <- if (max(xii,x5)==xii){
  p1
} else if (max(xii,x5)==x5){
  p2
}
xl3 <- if (max(xiii,x6)==xiii){
  p1
} else if (max(xiii,x6)==x6){
  p2
}

#Code problems

if (xl1 == p1) {
  diag1 = "\\theta_1"
  misdiag1 = "\\theta_2"
} else {
  diag1 = "\\theta_2"
  misdiag1 = "\\theta_1"
}
if (xl2 == p1) {
  diag2 = "\\theta_1"
  misdiag2 = "\\theta_2"
} else {
  diag2 = "\\theta_2"
  misdiag2 = "\\theta_1"
}
if (xl3 == p1) {
  diag3 = "\\theta_1"
  misdiag3 = "\\theta_2"
} else {
  diag3 = "\\theta_2"
  misdiag3 = "\\theta_1"
}

#Probabilities needed for misdiagnosis
pm1 <- if (diag1=="\\theta_1"){
  rand4
} else if (diag1=="\\theta_2"){
  rand1
}

pm2 <- if (diag2=="\\theta_1"){
  rand5
} else if (diag2=="\\theta_2"){
  rand2
}

pm3 <- if (diag3=="\\theta_1"){
  rand6
} else if (diag3=="\\theta_2"){
  rand3
}

pt1 <- if (diag1=="\\theta_1"){
  pr2
} else {
  pr1
}

pt2 <- if (diag2=="\\theta_1"){
  pr2
} else {
  pr1
}

pt3 <- if (diag3=="\\theta_1"){
  pr2
} else {
  pr1
}

pmis = pm1*pt1+pm2*pt2+pm3*pt3
mis = 100*pmis
```

Solution
========

### Posterior probabilities

First we must calculate the **posterior probabilities**, $\Pr(\theta_{1}|x_i)$ and $\Pr(\theta_{2}|x_i)$ for $i=1,2,3$. We can use **Bayes Theorem** as follows:

`r x1`

`r x2`

`r x3`  

It follows that:

$$
\begin{aligned}
\Pr(\theta_{2}|x_{1}) &= 1-\Pr(\theta_{1}|x_{1})= `r x4` \\
\Pr(\theta_{2}|x_{2}) &= 1-\Pr(\theta_{1}|x_{2})= `r x5` \\
\Pr(\theta_{2}|x_{3}) &= 1-\Pr(\theta_{1}|x_{3})= `r x6`
\end{aligned}
$$
We can summarise these posterior probabilities $\Pr(\theta_j|x_i)$ in the follwing table:

|                                 | $$x_1$$   | $$x_2$$   | $$x_3$$   |
| :------------------------------ | --------: | --------: | --------: |
| $\theta_{1}$: `r p1`            | `r xi`    | `r xii`   | `r xiii`  |
| $\theta_{2}$: `r p2`            | `r x4`    | `r x5`    | `r x6`    |

### Diagnostic rule

Using this table we can see that

* If $x_1$ is observed (`r s1`), the most plausible problem is $`r diag1`$ (`r xl1`).
* If $x_2$ is observed (`r s2`), the most plausible problem is $`r diag2`$ (`r xl2`).
* If $x_3$ is observed (`r s3`), the most plausible problem is $`r diag3`$ (`r xl3`).

From these results, we can construct a diagnostic rule:

| **Symptom**                       | **Diagnosis**                  |
| :-------------------------------- | :----------------------------- |
| `r s1`, $x_{1}$:                  | `r xl1`, $`r diag1`$           |
| `r s2`, $x_{2}$:                  | `r xl2`, $`r diag2`$           |
| `r s3`, $x_{3}$:                  | `r xl3`, $`r diag3`$           |  

### Probability of misdiagnosis

The probability of misdiagnosing the problem is:

$$
\begin{aligned}
\Pr(\text{Misdiagnosis}) &= \Pr(`r misdiag1`, x_{1})+\Pr(`r misdiag2`, x_{2}) +\Pr(`r misdiag3`,x_{3}) \\
&= \Pr(x_{1}|`r misdiag1`)\Pr(`r misdiag1`)+\Pr(x_{2}|`r misdiag2`)\Pr(`r misdiag2`)+\Pr(x_{3}|`r misdiag3`)\Pr(`r misdiag3`) \\
&= `r pm1` \times `r pt1`+`r pm2` \times `r pt2`+`r pm3` \times `r pt3` \\
&= `r pmis`
\end{aligned}
$$

So we believe about `r mis`% of diagnoses will be misdiagnoses.