---
output: html_document
---
```{r data generation, echo = FALSE, results = "hide"}
x<- round(runif(6,0,6),1)
a<- sample(c(1:3),1)
b<-round(runif(1,0,1),1)
x2<- round(runif(6,0,6),1)
mean1<- round(mean(x),2)
mean2<- round(mean(x2),2)
a2<-a+6
b2<-b+6*mean1
a3<-a2+6
b3<-b2+6*mean2
```

Question
========
Times between earthquakes are assumed to follow independent $Exp(\theta)$ distributions. The following data is observed:
`r x`. Find the posterior using a $Ga(`r a`, `r b`)$ prior.

Later, we observe some more data: `r x2`. Update the posterior using this data.

Solution
========
Consider the first six observations. We observe $n=6$ observations from a $Exp(\theta)$ distribution with $\bar{x}=`r mean1`$. Our prior is $Ga(`r a`, `r b`)$. 

We know from lectures that our first posterior should is $Ga(`r a`+n,`r b`+n\bar{x})$.

Therefore our first posterior is $Ga(`r a2`, `r b2`)$.

Now consider the second set of data, taken independently from a $Exp(\theta)$ distribution. The mean of this data is $\bar{y}=`r mean2`$. Our prior for this set of data is $Ga(`r a2`,`r b2`)$ from our previous analysis. Using the formulae from lectures again, our posterior is now $Ga(`r a2`+m,`r b2`+n\bar{y})$. So our final posterior is $Ga(`r a3`,`r b3`)$. 

Meta-information
================
extype: num
exsolution: 1
exname: sequential bayes
extol: 0.01