---
output: html_document
---

```{r data generation, echo = FALSE, results = "hide"}
a<-sample(c(14:18),1)
b<-sample(c(4,9,16),1)
c<-sample(c(1:20),1)
d<-sample(c(1:10),1)
t<-sample(seq(0.1,0.3,length=3),1)


```

Question
========

Suppose we are researching the temperature $X$ (in °C) at a specific location.
It is assumed that $X \sim N(\mu,\frac{1}{\tau})$ with $\tau=`r t`$.

A local weather expert tells you that a typical temperature in the region is `r a`, and that 95% of the time, the temperature is between `r a-2*sqrt(b)`°C and `r a+2*sqrt(b)`°C.
Based on this, you choose a $N(`r a`,`r sqrt(b)`^2)$ prior distribution.

1.
Explain why this prior is a good choice to capture the expert's beliefs.

2.
Explain why $Exp(\frac{1}{`r a`})$ would be a bad choice of prior.

3.
Under the prior, $\Pr(\mu>18)=`r round(1-pnorm(18,a,sqrt(b)),4)`$.
Use this information to come up with a prior refinement question to ask the expert.

4.
A single observation $x=`r c`$ is made.
Show that the posterior is a $N(`r round(((1/b)*(a)+(t*c))/(1/b+t),2)`, `r round(1/(1/b+t),2)`)$ distribution.

5.
It is decided to change the prior to incorporate the constraint $\mu>`r d`$.
Write down the density of the resulting posterior up to proportionality.